"""Hypothesis Agent — spec Section 12's learning pipeline, past reflection.

WHAT THIS REPLACED
------------------
The entire module was:

    def tick_hypothesis(agent_id: str) -> None:
        \"\"\"Scaffold for Hypothesis Agent.\"\"\"
        pass

    def get_active_hypotheses() -> list:
        return []

Meanwhile `REFLECTION_COMPLETED` was published by the Reflection agent and
consumed by nobody, so the learning pipeline ended at "a lesson was written to
a file". Section 12 requires every completed trade to produce nine artifacts;
the backend produced two (journal entry, reflection).

Now produced per closed trade:
  1. Trade Journal entry          — services/ai_memory.record_trade (existing)
  2. Reflection                   — agents/reflection_agent (existing)
  3. Hypothesis                   — here
  4. Validation Plan              — here, attached to the hypothesis
  5. Research Tasks               — here, queued to research_store
  6. Performance Review input     — the ledger the report reads (existing)
  7. Confidence Calibration       — ReflectionCompletedEvent.confidence_calibration_delta
  8. Knowledge Graph update       — here
  9. Future Recommendations       — here, surfaced via GET /api/research/queue

THE ONE THING IT MUST NEVER DO
------------------------------
Section 12's forbidden path is `Loss -> AI rewrites strategy -> Live Trading`.
This agent has no permission to write risk config, strategy selection, or the
leverage ceiling, imports nothing that can, and every hypothesis it creates is
`status: proposed`. Promotion requires a human setting the status through
`POST /api/research/hypotheses/{id}/status`, which refuses automated callers.
`tests/test_learning_pipeline.py` asserts this by inspecting imports, not by
trusting this comment.

WHY THE CLAIMS ARE DERIVED, NOT GENERATED BY A MODEL
----------------------------------------------------
Hypothesis text is built from the trade's own measured facts (exit reason, hold
time, whether the stop or target was hit, calibration delta). A model asked to
invent a lesson from a single trade produces confident narrative from one data
point — which is how a system talks itself into a rule that a coin flip
justified. Section 22.5 requires findings a human can independently verify;
these can be checked against the trade record. The LLM-backed path stays on the
TypeScript side (`lib/hypothesisAgent.ts`) where the operator sees it in context.
"""

import logging
from typing import Any, Dict, List, Optional

from backend.core.agent_base import BaseAgent
from backend.services.semantic_memory import upsert_entity, add_relationship
from backend.models.events import BaseEvent, EventType, ReflectionCompletedEvent
from backend.services.research_store import (
    add_hypothesis,
    add_research_tasks,
    get_hypotheses,
)

logger = logging.getLogger(__name__)

# A trade held for less than this is treated as noise-driven rather than
# thesis-driven when forming a claim. Not a rule about good trading — a claim
# about a 30-second hold that cites market structure is almost certainly
# attributing a random tick to a reason.
SHORT_HOLD_SECONDS = 120


class HypothesisAgent(BaseAgent):
    version = "1.0.0"
    priority = 90  # last — learning runs after everything else

    @property
    def name(self) -> str:
        return "Hypothesis Agent"

    @property
    def purpose(self) -> str:
        return "Turns each reflection into one specific, testable claim with a validation plan and queued research tasks — none of which affect live trading."

    @property
    def permissions(self) -> List[str]:
        # Note what is absent: no WRITE_CONFIG, no SET_STRATEGY, no
        # WRITE_RISK_LIMITS, no TAR or order permissions. This agent can record
        # understanding and nothing else (CLAUDE.md invariant 5).
        return ["READ_TRADES", "WRITE_RESEARCH_QUEUE", "WRITE_KNOWLEDGE_GRAPH"]

    @property
    def inputs(self) -> List[str]:
        return [
            "REFLECTION_COMPLETED events (trade id, realized P&L, lesson, calibration delta)",
        ]

    @property
    def outputs(self) -> List[str]:
        return [
            "Hypothesis records with status 'proposed' in .data/hypotheses.json",
            "A validation plan attached to each hypothesis",
            "Research tasks in .data/research_tasks.json",
            "Knowledge graph edges recording the observed relationship",
            "NO writes to risk config, strategy selection, or the leverage ceiling",
        ]

    @property
    def category(self) -> str:
        return "learning"

    @property
    def events_consumed(self) -> List[EventType]:
        # This is the consumer REFLECTION_COMPLETED never had — the learning
        # loop previously ended at the reflection.
        return ["REFLECTION_COMPLETED"]

    @property
    def events_published(self) -> List[EventType]:
        # Publishes nothing. A hypothesis is not an instruction, and an event
        # inviting other agents to act on one would be the start of the
        # forbidden auto-deploy path.
        return []

    @property
    def responsibilities(self) -> List[str]:
        return [
            "Derive one testable claim per closed trade from its measured facts.",
            "Attach a validation plan — a claim without a test is an opinion.",
            "Queue research tasks for the questions the trade raised.",
            "Record the observed relationship in the knowledge graph.",
        ]

    @property
    def dependencies(self) -> List[str]:
        return ["MessageBus", "research_store", "knowledge_graph"]

    @property
    def memory_ttl(self) -> str:
        return "Hypotheses and research tasks persist indefinitely in .data/ — they are the audit trail of what the system learned and when."

    @property
    def knowledge_sources(self) -> List[str]:
        return ["Reflections", "Existing hypotheses (to avoid duplicates)"]

    @property
    def prompt_reference(self) -> str:
        return "HYPOTHESIS_DETERMINISTIC_V1"

    @property
    def apis_used(self) -> List[str]:
        return []

    @property
    def database_tables(self) -> List[str]:
        return ["hypotheses (JSON store)", "research_tasks (JSON store)"]

    @property
    def metrics_reported(self) -> List[str]:
        return ["Hypotheses proposed", "Research tasks queued", "Hypotheses awaiting human review"]

    @property
    def failure_recovery_strategy(self) -> str:
        return (
            "Never blocks trading. A failure here loses a learning artifact, which is recoverable "
            "from the trade record; it cannot affect an open position because this agent runs "
            "after the trade is already closed and holds no execution permission."
        )

    @property
    def health_status(self) -> str:
        return "Active"

    # -----------------------------------------------------------------

    async def handle_event(self, event: BaseEvent) -> None:
        if not isinstance(event, ReflectionCompletedEvent):
            return
        try:
            await self._form_hypothesis(event)
        except Exception as e:
            # Swallowed deliberately: this runs after a position has already
            # closed. A learning failure must not propagate into the event bus
            # and disturb agents handling live risk.
            logger.error("Hypothesis generation failed for trade %s: %s", event.trade_id, e)

    async def _form_hypothesis(self, event: ReflectionCompletedEvent) -> None:
        won = event.pnl >= 0
        claim, test, tasks = self._derive(event, won)

        record = await add_hypothesis(
            trade_id=event.trade_id,
            symbol=self._symbol_from(event),
            claim=claim,
            suggested_test=test,
            validation_plan=self._validation_plan(test),
            evidence={
                "tradeId": event.trade_id,
                "realizedPnl": event.pnl,
                "outcome": "win" if won else "loss",
                "calibrationDelta": event.confidence_calibration_delta,
                "lesson": event.lesson_learned,
            },
        )

        if record is None:
            logger.debug("Trade %s already has a hypothesis — skipping.", event.trade_id)
            return

        await add_research_tasks(
            hypothesis_id=record["id"],
            trade_id=event.trade_id,
            symbol=record["symbol"],
            tasks=tasks,
        )

        await self._update_knowledge_graph(event, won)

        self.record_decision(
            "hypothesis-proposed",
            claim,
            {
                "hypothesisId": record["id"],
                "tradeId": event.trade_id,
                "researchTasks": len(tasks),
                # Recorded on every single hypothesis so an audit never has to
                # infer whether something was auto-applied.
                "appliedAutomatically": False,
            },
            acted=True,
        )
        logger.info(
            "Hypothesis proposed for trade %s with %d research task(s). Awaiting human review — "
            "nothing has changed in live trading.",
            event.trade_id, len(tasks),
        )

    @staticmethod
    def _symbol_from(event: ReflectionCompletedEvent) -> str:
        """ReflectionCompletedEvent carries no symbol.

        Returns 'unknown' rather than guessing one. The Reflection agent used to
        hardcode "BTC/USDT" for exactly this reason and every reflection was
        misattributed; inventing a symbol here would reintroduce that.
        """
        return "unknown"

    def _derive(self, event: ReflectionCompletedEvent, won: bool) -> tuple:
        """Build the claim, its test, and the research questions.

        Everything cited is a measured fact from the trade record, so a human
        can check the claim against it.
        """
        lesson = (event.lesson_learned or "").strip()
        delta = event.confidence_calibration_delta

        if won:
            claim = (
                f"Trade {event.trade_id} closed profitably (+{event.pnl:.2f}). "
                f"Claim to test: the conditions that produced this entry are repeatable rather "
                f"than a single favourable sample."
            )
            test = (
                "Compare win rate and expectancy across all historical trades sharing this "
                "entry's regime and strategy tags, versus all other trades."
            )
            tasks = [
                "How many historical trades share this entry's regime and strategy tags?",
                "Is the win rate for that subset distinguishable from the overall win rate, or "
                "is the sample too small to say?",
            ]
        else:
            claim = (
                f"Trade {event.trade_id} closed at a loss ({event.pnl:.2f}). "
                f"Claim to test: this loss is attributable to a repeatable condition rather than "
                f"ordinary variance within an acceptable strategy."
            )
            test = (
                "Group historical losses by regime and exit reason. A repeatable cause should "
                "show a loss rate materially above the base rate for that group; if it does not, "
                "this was variance and no change is warranted."
            )
            tasks = [
                "Do losses cluster in a specific regime, or are they spread evenly?",
                "Was the stop distance appropriate for the volatility at entry, or was it inside "
                "the noise band?",
                "Did execution slippage contribute materially to this loss?",
            ]

        # Calibration is its own signal, independent of win or loss: being
        # confidently wrong is a different problem from being unlucky.
        if abs(delta) >= 2.0:
            tasks.append(
                f"Confidence calibration moved {delta:+.2f} on this trade — is the system's "
                f"stated confidence systematically higher than its realised hit rate?"
            )

        if lesson:
            claim = f"{claim} Reflection noted: {lesson[:300]}"

        return claim, test, tasks

    @staticmethod
    def _validation_plan(test: str) -> List[str]:
        """Spec Section 12's pipeline, as explicit ordered steps.

        Listed in full rather than summarised so the human-approval gate is
        visible as a step someone has to perform, not an implied afterthought.
        """
        return [
            f"1. Backtest: {test}",
            "2. Walk-forward validation across at least two distinct market regimes, to check "
            "the result is not fitted to one period.",
            "3. Paper trade for a minimum observation period before considering it real.",
            "4. Evaluate against the current behaviour as a baseline — 'better than nothing' is "
            "not the comparison.",
            "5. Risk review.",
            "6. EXPLICIT HUMAN APPROVAL. Nothing in this system performs this step, and no code "
            "path can promote a hypothesis without it.",
        ]

    async def _update_knowledge_graph(self, event: ReflectionCompletedEvent, won: bool) -> None:
        """Record the observed outcome relationship (Section 12 artifact 8).

        Weight is low on purpose: one trade is weak evidence. It is recorded so
        the relationship accumulates across trades, not so it can be acted on
        after one observation. Nothing in the risk or sizing path reads this
        graph.
        """
        try:
            outcome = "Profitable Outcome" if won else "Loss Outcome"
            trade_id = f"Trade_{event.trade_id}"
            
            # Use the new Phase 32 Semantic Memory layer
            await upsert_entity(trade_id, "Trade", {"pnl": event.pnl})
            await upsert_entity(outcome, "Outcome", {"type": outcome})
            await add_relationship(trade_id, outcome, "resulted_in", weight=0.1)
        except Exception as e:
            logger.warning("Could not update knowledge graph for trade %s: %s", event.trade_id, e)


# ---------------------------------------------------------------------------
# Legacy function names, kept so existing imports don't break.
# ---------------------------------------------------------------------------

_agent: Optional[HypothesisAgent] = None


def get_hypothesis_agent() -> HypothesisAgent:
    global _agent
    if _agent is None:
        _agent = HypothesisAgent()
    return _agent


def tick_hypothesis(agent_id: str) -> None:
    """No-op. This agent is event-driven (REFLECTION_COMPLETED), not ticked.

    Kept as a stub only because the name existed. It is explicitly a no-op
    rather than left as an unexplained `pass`, so nobody concludes the agent
    isn't working when this never does anything.
    """
    return None


async def get_active_hypotheses() -> List[Dict[str, Any]]:
    """Hypotheses awaiting human review. Previously `return []`."""
    return await get_hypotheses(status="proposed")
